[tool.poetry]
name = "hello"
version = "0.1.0"
description = "Hello World com Python"
authors = ["Edilson Wagner Ribeiro Júnior"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
